// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.Data;

#nullable disable

namespace SubastaYa.Infrastructure.Migrations
{
    [DbContext(typeof(SubastaYaContext))]
    [Migration("20260901232244_AddAccionAndSeedData")]
    partial class AddAccionAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoDisponible = 0.00m,
                            SaldoRetenido = 0.00m,
                            SaldoTotal = 0.00m,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            SaldoDisponible = 105000.00m,
                            SaldoRetenido = 45000.00m,
                            SaldoTotal = 150000.00m,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            SaldoDisponible = 200000.00m,
                            SaldoRetenido = 0.00m,
                            SaldoTotal = 200000.00m,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            SaldoDisponible = 500.00m,
                            SaldoRetenido = 0.00m,
                            SaldoTotal = 500.00m,
                            UsuarioId = 4
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlIcono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología",
                            UrlIcono = "https://images.unsplash.com/photo-1519389950473-47ba0277781c"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables",
                            UrlIcono = "https://images.unsplash.com/photo-1563245372-f21724e3856d"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria",
                            UrlIcono = "https://images.unsplash.com/photo-1523381210434-271e8be1f52b"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos",
                            UrlIcono = "https://images.unsplash.com/photo-1503376780353-7e6692767b70"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompradorId = 3,
                            Fecha = new DateTime(2026, 9, 1, 19, 30, 0, 0, DateTimeKind.Utc),
                            Monto = 35000.00m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompradorId = 2,
                            Fecha = new DateTime(2026, 9, 1, 19, 45, 0, 0, DateTimeKind.Utc),
                            Monto = 45000.00m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompradorId = 2,
                            Fecha = new DateTime(2026, 8, 31, 15, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 90000.00m,
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subastas_Estado", "[Estado] IN ('PROGRAMADA', 'ACTIVA', 'FINALIZADA', 'DESIERTA')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Consola de última generación en perfecto estado con joystick DualSense",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 1, 23, 45, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 9, 1, 19, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 5000.00m,
                            PrecioBase = 30000.00m,
                            Titulo = "PlayStation 5 Digital Edition",
                            UrlImagen = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db",
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Carta coleccionable en estado Near Mint, protegida en acrílico",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 1, 23, 15, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 9, 1, 19, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 1000.00m,
                            PrecioBase = 10000.00m,
                            Titulo = "Carta Pokémon Charizard 1st Edition",
                            UrlImagen = "https://images.unsplash.com/photo-1613770920235-94578b87192f",
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Descripcion = "Vehículo sedán con 25.000 km, único dueño, todos los services oficiales",
                            Estado = "PROGRAMADA",
                            FechaFin = new DateTime(2026, 9, 3, 20, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 100000.00m,
                            PrecioBase = 15000000.00m,
                            Titulo = "Toyota Corolla 2022 2.0 SEG CVT",
                            UrlImagen = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Laptop profesional 16GB RAM, batería con 40 ciclos de carga",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 8, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 5000.00m,
                            PrecioBase = 80000.00m,
                            Titulo = "MacBook Pro M2 14 pulgadas 512GB",
                            UrlImagen = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descripcion = "Campera de cuero genuino talle L, importada",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2026, 8, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            IncrementoMinimo = 2000.00m,
                            PrecioBase = 25000.00m,
                            Titulo = "Campera de Cuero Vintage Hombre",
                            UrlImagen = "https://images.unsplash.com/photo-1551028719-00167b16eac5",
                            VendedorId = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TransaccionLedger", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransaccionLedger_Tipo", "[Tipo] IN ('DEPOSITO', 'RETENCION', 'LIBERACION', 'PAGO', 'COBRO')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 150000.00m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 1, 19, 45, 0, 0, DateTimeKind.Utc),
                            Monto = 45000.00m,
                            SubastaId = 1,
                            Tipo = "RETENCION"
                        },
                        new
                        {
                            Id = 3,
                            BilleteraId = 3,
                            Fecha = new DateTime(2026, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 200000.00m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 4,
                            BilleteraId = 3,
                            Fecha = new DateTime(2026, 9, 1, 19, 30, 0, 0, DateTimeKind.Utc),
                            Monto = 35000.00m,
                            SubastaId = 1,
                            Tipo = "RETENCION"
                        },
                        new
                        {
                            Id = 5,
                            BilleteraId = 3,
                            Fecha = new DateTime(2026, 9, 1, 19, 45, 0, 0, DateTimeKind.Utc),
                            Monto = 35000.00m,
                            SubastaId = 1,
                            Tipo = "LIBERACION"
                        },
                        new
                        {
                            Id = 6,
                            BilleteraId = 4,
                            Fecha = new DateTime(2026, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 500.00m,
                            Tipo = "DEPOSITO"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vendedor Test"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador 1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador 2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Sin Fondos"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("AuditoriaLogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Domain.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Comprador")
                        .WithMany("Pujas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Vendedor")
                        .WithMany("Subastas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Billetera", "Billetera")
                        .WithMany("TransaccionesLedger")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany("TransaccionesLedger")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Navigation("TransaccionesLedger");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");

                    b.Navigation("TransaccionesLedger");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AuditoriaLogs");

                    b.Navigation("Billetera")
                        .IsRequired();

                    b.Navigation("Pujas");

                    b.Navigation("Subastas");
                });
#pragma warning restore 612, 618
        }
    }
}
